version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - '8080:80'
    volumes:
      - ./data/www:/www
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./data/db:/var/lib/mysql
