version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - '8080:80'
    volumes:
      - ./data/www:/www
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - '3406:3306'
    volumes:
      - ./data/db:/var/lib/mysql
