version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
      args:
        - HOST_USER_ID
    ports:
      - '8080:80'
    volumes:
      - ./data/www:/www
      # If SELinux is causing problems with these volume mounts,
      # you may try appending `:Z` to the host directory to
      # ensure MCS labels are added:
      # - ./data/www:/www:Z
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
      args:
        - HOST_USER_ID
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./data/db:/var/lib/mysql
      # - ./data/db:/var/lib/mysql:Z
